"""Remove GamePicksStats table

Revision ID: 02b0537049eb
Revises: deb95bf36c0f
Create Date: 2026-02-04 10:11:42.793592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b0537049eb'
down_revision = 'deb95bf36c0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('game_picks_stats')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_picks_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('round_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('round_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('team_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('seed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('region_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('num_picks', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='game_picks_stats_pkey')
    )
    # ### end Alembic commands ###
