"""Add reset code and expiration to User

Revision ID: 2ae2dbede8d0
Revises: d58fafbcf8a7
Create Date: 2024-03-18 18:47:57.697944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ae2dbede8d0'
down_revision = 'd58fafbcf8a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reset_code', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('reset_code_expiration', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('reset_code_expiration')
        batch_op.drop_column('reset_code')

    # ### end Alembic commands ###
