"""Add efficiency and probability fields

Revision ID: 3798a3d2f671
Revises: d7a716c04475
Create Date: 2026-03-16 00:58:20.613350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3798a3d2f671'
down_revision = 'd7a716c04475'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_probability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('probability', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avg_o_rating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('expected_standings_dirty', sa.Boolean(), nullable=False, server_default=sa.text('true')))

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('off_efficiency', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('def_efficiency', sa.Float(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expected_score', sa.Float(), nullable=False, server_default='0.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('expected_score')

    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('def_efficiency')
        batch_op.drop_column('off_efficiency')

    with op.batch_alter_table('pool', schema=None) as batch_op:
        batch_op.drop_column('expected_standings_dirty')
        batch_op.drop_column('avg_o_rating')

    op.drop_table('game_probability')
    # ### end Alembic commands ###
