"""Initial migration.

Revision ID: 4163da88fad9
Revises: 
Create Date: 2024-01-12 07:48:54.954585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4163da88fad9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('r1score', sa.Integer(), nullable=False),
    sa.Column('r2score', sa.Integer(), nullable=False),
    sa.Column('r3score', sa.Integer(), nullable=False),
    sa.Column('r4score', sa.Integer(), nullable=False),
    sa.Column('r5score', sa.Integer(), nullable=False),
    sa.Column('r6score', sa.Integer(), nullable=False),
    sa.Column('currentscore', sa.Integer(), nullable=False),
    sa.Column('maxpossiblescore', sa.Integer(), nullable=False),
    sa.Column('tiebreaker_winner', sa.Integer(), nullable=False),
    sa.Column('tiebreaker_loser', sa.Integer(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
