"""Add last_bracket_save to User

Revision ID: 49f0edcf893f
Revises: 803af5c9a887
Create Date: 2024-01-20 08:05:52.614093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49f0edcf893f'
down_revision = '803af5c9a887'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_bracket_save', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_bracket_save')

    # ### end Alembic commands ###
