"""Added hidden column to Thread and Post

Revision ID: 5a83f5bfb2fd
Revises: 15e056a50706
Create Date: 2024-01-21 21:23:53.434773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a83f5bfb2fd'
down_revision = '15e056a50706'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=True))

    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hidden', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('thread', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('hidden')

    # ### end Alembic commands ###
