"""Add is_bracket_valid to User

Revision ID: 803af5c9a887
Revises: de5ca902ebb1
Create Date: 2024-01-15 16:18:35.320682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803af5c9a887'
down_revision = 'de5ca902ebb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_bracket_valid', sa.Boolean(), nullable=False, server_default=sa.sql.expression.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('is_bracket_valid')

    # ### end Alembic commands ###
