"""Added time zone to User

Revision ID: c20a8e7e706b
Revises: 6dfcba0b247a
Create Date: 2024-01-13 17:00:18.753822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20a8e7e706b'
down_revision = '6dfcba0b247a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('time_zone', sa.String(length=50), nullable=False, server_default='UTC'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('time_zone')

    # ### end Alembic commands ###
