"""Add EspnSyncLog table

Revision ID: d7a716c04475
Revises: f8cdb2b13198
Create Date: 2026-02-27 00:42:45.537262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7a716c04475'
down_revision = 'f8cdb2b13198'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('espn_sync_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(), nullable=False),
    sa.Column('games_updated', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('espn_sync_log')
    # ### end Alembic commands ###
