"""Add espn team and id

Revision ID: f8cdb2b13198
Revises: 02b0537049eb
Create Date: 2026-02-27 00:18:14.390695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8cdb2b13198'
down_revision = '02b0537049eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('espn_team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('espn_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=150), nullable=False),
    sa.Column('short_display_name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('espn_id')
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.add_column(sa.Column('espn_team_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('espn_play_in_team_2_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('is_play_in_slot', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_column('is_play_in_slot')
        batch_op.drop_column('espn_play_in_team_2_id')
        batch_op.drop_column('espn_team_id')

    op.drop_table('espn_team')
    # ### end Alembic commands ###
